/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  reg [15:0] a;
  
  reg [15:0] b;
  
  reg [15:0] op;
  
  reg [0:0] error;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  localparam IDLE_state = 4'd0;
  localparam ADD_state = 4'd1;
  localparam SUB_state = 4'd2;
  localparam AND_state = 4'd3;
  localparam OR_state = 4'd4;
  localparam XOR_state = 4'd5;
  localparam A_state = 4'd6;
  localparam INVA_state = 4'd7;
  localparam SHL_state = 4'd8;
  localparam SHR_state = 4'd9;
  localparam SRA_state = 4'd10;
  localparam CMPEQ_state = 4'd11;
  localparam CMPLT_state = 4'd12;
  localparam CMPLE_state = 4'd13;
  localparam ERR_state = 4'd14;
  
  reg [3:0] M_state_d, M_state_q = IDLE_state;
  reg [15:0] M_sum_d, M_sum_q = 1'h0;
  reg [31:0] M_counter_d, M_counter_q = 1'h0;
  reg [0:0] M_manual_d, M_manual_q = 1'h0;
  
  localparam CYCLE = 5'h1a;
  
  wire [16-1:0] M_alu_alu;
  wire [1-1:0] M_alu_z;
  wire [1-1:0] M_alu_v;
  wire [1-1:0] M_alu_n;
  reg [6-1:0] M_alu_alufn;
  reg [16-1:0] M_alu_a;
  reg [16-1:0] M_alu_b;
  alu_2 alu (
    .alufn(M_alu_alufn),
    .a(M_alu_a),
    .b(M_alu_b),
    .alu(M_alu_alu),
    .z(M_alu_z),
    .v(M_alu_v),
    .n(M_alu_n)
  );
  
  always @* begin
    M_state_d = M_state_q;
    M_manual_d = M_manual_q;
    M_counter_d = M_counter_q;
    M_sum_d = M_sum_q;
    
    error = io_dip[0+0+0-:1];
    M_alu_a = 16'h0001 + error;
    M_alu_b = 16'h0001;
    M_alu_alufn = 6'h00;
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    
    case (M_state_q)
      IDLE_state: begin
        M_manual_d = 1'h1;
        if (io_button[0+0-:1] == 1'h1) begin
          M_state_d = ADD_state;
          M_manual_d = 1'h0;
        end
        if (io_dip[16+7+0-:1] == 1'h1) begin
          M_state_d = ADD_state;
        end
        if (io_dip[16+6+0-:1] == 1'h1) begin
          M_state_d = SUB_state;
        end
        if (io_dip[16+5+0-:1] == 1'h1) begin
          M_state_d = AND_state;
        end
        if (io_dip[16+4+0-:1] == 1'h1) begin
          M_state_d = OR_state;
        end
        if (io_dip[16+3+0-:1] == 1'h1) begin
          M_state_d = XOR_state;
        end
        if (io_dip[16+2+0-:1] == 1'h1) begin
          M_state_d = A_state;
        end
        if (io_dip[16+1+0-:1] == 1'h1) begin
          M_state_d = INVA_state;
        end
        if (io_dip[16+0+0-:1] == 1'h1) begin
          M_state_d = SHL_state;
        end
        if (io_dip[8+7+0-:1] == 1'h1) begin
          M_state_d = SHR_state;
        end
        if (io_dip[8+6+0-:1] == 1'h1) begin
          M_state_d = SRA_state;
        end
        if (io_dip[8+5+0-:1] == 1'h1) begin
          M_state_d = CMPEQ_state;
        end
        if (io_dip[8+4+0-:1] == 1'h1) begin
          M_state_d = CMPLT_state;
        end
        if (io_dip[8+3+0-:1] == 1'h1) begin
          M_state_d = CMPLE_state;
        end
      end
      ADD_state: begin
        M_counter_d = M_counter_q + 1'h1;
        op = 16'h0002;
        M_sum_d = M_alu_alu;
        io_led[0+7-:8] = M_sum_q[0+7-:8];
        io_led[8+7-:8] = M_sum_q[8+7-:8];
        if (op == M_sum_q) begin
          io_led[16+7+0-:1] = 1'h1;
        end
        if (M_counter_q[26+0-:1] == 1'h1) begin
          if (M_manual_q == 1'h1) begin
            M_state_d = IDLE_state;
            M_counter_d = 1'h0;
          end else begin
            led[0+0-:1] = M_alu_alu;
            if (op == M_sum_q) begin
              M_counter_d = 1'h0;
              M_state_d = IDLE_state;
            end else begin
              M_counter_d = 1'h0;
              M_state_d = ERR_state;
            end
          end
        end
      end
      ERR_state: begin
        M_counter_d = M_counter_q + 1'h1;
        io_led[16+7-:8] = $signed(2'h3);
        led[0+0-:1] = M_alu_alu;
        if (M_counter_q[26+0-:1] == 1'h1) begin
          M_state_d = IDLE_state;
          M_counter_d = 1'h0;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    M_sum_q <= M_sum_d;
    M_counter_q <= M_counter_d;
    M_manual_q <= M_manual_d;
    M_state_q <= M_state_d;
  end
  
endmodule
