/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 16
     DIV = 26
     TOP = 5
     UP = 0
*/
module counter_6 (
    input clk,
    input rst,
    output reg [15:0] value,
    input start
  );
  
  localparam SIZE = 5'h10;
  localparam DIV = 5'h1a;
  localparam TOP = 3'h5;
  localparam UP = 1'h0;
  
  
  reg [41:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 29'h17ffffff;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[26+15-:16];
    if (start) begin
      if (1'h0) begin
        M_ctr_d = M_ctr_q + 1'h1;
        if (1'h1 && M_ctr_q == 29'h17ffffff) begin
          M_ctr_d = 1'h0;
        end
      end else begin
        M_ctr_d = M_ctr_q - 1'h1;
        if (1'h1 && M_ctr_q == 1'h0) begin
          M_ctr_d = 29'h17ffffff;
        end
      end
    end else begin
      M_ctr_d = 29'h17ffffff;
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
