/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [3:0] io_led,
    output reg [7:0] io_seg,
    output reg [7:0] io_sel,
    input [3:0] io_button
  );
  
  
  
  reg rst;
  
  reg [15:0] ones;
  
  reg [15:0] tens;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  reg [31:0] M_seed_d, M_seed_q = 1'h0;
  wire [16-1:0] M_ctr_value;
  counter_2 ctr (
    .clk(clk),
    .rst(rst),
    .value(M_ctr_value)
  );
  wire [7-1:0] M_player_1_seg_seg;
  wire [3-1:0] M_player_1_seg_sel;
  reg [12-1:0] M_player_1_seg_values;
  multi_seven_seg_3 player_1_seg (
    .clk(clk),
    .rst(rst),
    .values(M_player_1_seg_values),
    .seg(M_player_1_seg_seg),
    .sel(M_player_1_seg_sel)
  );
  wire [7-1:0] M_player_2_seg_seg;
  wire [3-1:0] M_player_2_seg_sel;
  reg [12-1:0] M_player_2_seg_values;
  multi_seven_seg_3 player_2_seg (
    .clk(clk),
    .rst(rst),
    .values(M_player_2_seg_values),
    .seg(M_player_2_seg_seg),
    .sel(M_player_2_seg_sel)
  );
  wire [7-1:0] M_timer_seg_seg;
  wire [3-1:0] M_timer_seg_sel;
  reg [12-1:0] M_timer_seg_values;
  multi_seven_seg_3 timer_seg (
    .clk(clk),
    .rst(rst),
    .values(M_timer_seg_values),
    .seg(M_timer_seg_seg),
    .sel(M_timer_seg_sel)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    tens = M_ctr_value / 4'ha;
    ones = M_ctr_value - tens * 4'ha;
    M_player_1_seg_values = {M_ctr_value[8+3-:4], tens[0+3-:4], ones[0+3-:4]};
    M_player_2_seg_values = {M_ctr_value[8+3-:4], tens[0+3-:4], ones[0+3-:4]};
    M_timer_seg_values = {M_ctr_value[8+3-:4], tens[0+3-:4], ones[0+3-:4]};
    io_seg = ~M_player_1_seg_seg;
    io_seg = ~M_player_2_seg_seg;
    io_seg = ~M_timer_seg_seg;
    io_sel[0+2-:3] = ~M_player_1_seg_sel;
    io_sel[3+2-:3] = ~M_player_2_seg_sel;
    io_sel[6+1-:2] = ~M_timer_seg_sel;
    io_led[0+3-:4] = 4'hf;
    io_led[0+3-:4] = ~io_button[0+3-:4];
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_seed_q <= 1'h0;
    end else begin
      M_seed_q <= M_seed_d;
    end
  end
  
endmodule
