/*
   This file was generated automatically by the Mojo IDE version B1.3.6.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module mojo_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input cclk,
    output reg spi_miso,
    input spi_ss,
    input spi_mosi,
    input spi_sck,
    output reg [3:0] spi_channel,
    input avr_tx,
    output reg avr_rx,
    input avr_rx_busy,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip,
    input carry,
    input sum
  );
  
  
  
  reg rst;
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_1 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    io_led = 24'h000000;
    led = 8'h00;
    spi_miso = 1'bz;
    spi_channel = 4'bzzzz;
    avr_rx = 1'bz;
    io_seg = 8'hff;
    io_sel = 4'hf;
    if (io_button[0+0-:1] == 1'h1) begin
      led[0+2-:3] = 1'h0;
      if (carry == 1'h0 && sum == 1'h0) begin
        io_led[16+7+0-:1] = 1'h1;
      end
      led[1+1-:2] = 1'h0;
      led[0+0-:1] = 1'h1;
      if (carry == 1'h0 && sum == 1'h1) begin
        io_led[16+6+0-:1] = 1'h1;
      end
      led[2+0-:1] = 1'h0;
      led[1+0-:1] = 1'h1;
      led[0+0-:1] = 1'h0;
      if (carry == 1'h0 && sum == 1'h1) begin
        io_led[16+5+0-:1] = 1'h1;
      end
      led[2+0-:1] = 1'h0;
      led[0+1-:2] = 1'h1;
      if (carry == 1'h1 && sum == 1'h0) begin
        io_led[16+4+0-:1] = 1'h1;
      end
      led[2+0-:1] = 1'h1;
      led[0+1-:2] = 1'h0;
      if (carry == 1'h0 && sum == 1'h1) begin
        io_led[16+3+0-:1] = 1'h1;
      end
      led[2+0-:1] = 1'h1;
      led[1+0-:1] = 1'h0;
      led[0+0-:1] = 1'h1;
      if (carry == 1'h1 && sum == 1'h0) begin
        io_led[16+2+0-:1] = 1'h1;
      end
      led[1+1-:2] = 1'h1;
      led[0+0-:1] = 1'h0;
      if (carry == 1'h1 && sum == 1'h0) begin
        io_led[16+1+0-:1] = 1'h1;
      end
      led[0+2-:3] = 1'h1;
      if (carry == 1'h1 && sum == 1'h1) begin
        io_led[16+0+0-:1] = 1'h1;
      end
    end
  end
endmodule
